### ISSUE TITLE
Proposal: introduce annotations

### ISSUE THREAD

**Issue by cub-uanic** [Ovid/Cor#20]
Please consider adding annotations, accessible in run-time (like in Java).
This will be useful for framework authors (like Spring / SpringBoot and others).

**Comment by happy-barney** [comment]
In perl world there already are two mechanisms capable of what java annotation does
- attributes
- traits

With [thoughts about extended slot mechanism](https://gist.github.com/happy-barney/d94d3a6d30b4529ab86ef5ea6c78a043) it's possible to cover class / instance attributes as well as method arguments.

As for classes, consumption of role (trait is in fact only role) may do the same thing.
Questionable entity is method. Following aforementioned patterns:
```
method foo {
    does 'Deprecated';
}
```

And there is behaviour of generated code ...

**Comment by Ovid** [comment]
This is resolved for the MVP. Further issues should be new tickets.
