### ISSUE TITLE
Clean up example code.

### ISSUE THREAD

**Issue by druud** [Ovid/Cor#43]
In 5.2.1 there is this example:
```
my @args = ... get list passed to new()
  unless ( !( @args % 2 ) ) {
    croak("even-sized list required");
}
```
which at least needs a ';' and a '#' and an indent-correction.

Straight rewrite:
```
my @args = ...;  # get list passed to new()
unless ( !( @args % 2 ) ) {
    croak("even-sized list required");
}
```
Alternative:
```
my @args = ...;  # get list passed to new()
@args % 2 and croak "even-sized list required";
```

**Comment by Ovid** [comment]
Thanks, druud! I'm happy to fix this, but if you want to issue a PR and be one of the contributors, I'd be happy to accept it :)

**Comment by Ovid** [comment]
This has been fixed. Thank you!
